-- =====================================================================
-- OpenID4VP (OpenID for Verifiable Presentations) Database Schema
-- WSO2 Identity Server Integration
-- 
-- This script creates the required tables for storing VP requests,
-- submissions, and presentation definitions.
-- =====================================================================



-- ---------------------------------------------------------------------
-- Table: IDN_VP_SUBMISSION
-- Description: Stores VP submissions (responses from wallets)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS IDN_VP_SUBMISSION (
    ID INTEGER AUTO_INCREMENT,
    SUBMISSION_ID VARCHAR(255) NOT NULL,
    REQUEST_ID VARCHAR(255) NOT NULL,
    VP_TOKEN TEXT,
    PRESENTATION_SUBMISSION TEXT,
    ERROR VARCHAR(255),
    ERROR_DESCRIPTION TEXT,
    VERIFICATION_STATUS VARCHAR(50),
    VERIFICATION_RESULT TEXT,
    SUBMITTED_AT BIGINT NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (ID),
    UNIQUE (SUBMISSION_ID, TENANT_ID)
);

-- Indexes for VP_SUBMISSION table
CREATE INDEX IDX_VP_SUB_REQUEST_ID ON IDN_VP_SUBMISSION(REQUEST_ID, TENANT_ID);
CREATE INDEX IDX_VP_SUB_VERIFICATION ON IDN_VP_SUBMISSION(VERIFICATION_STATUS, TENANT_ID);


-- ---------------------------------------------------------------------
-- Table: IDN_PRESENTATION_DEFINITION
-- Description: Stores presentation definition templates
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS IDN_PRESENTATION_DEFINITION (
    DEFINITION_ID VARCHAR(255) NOT NULL,
    RESOURCE_ID VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DEFINITION_JSON TEXT NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (DEFINITION_ID),
    UNIQUE (NAME, TENANT_ID)
);

-- Indexes for PRESENTATION_DEFINITION table
-- idx_pres_def_default removed
CREATE INDEX IDX_PRES_DEF_RESOURCE_ID ON IDN_PRESENTATION_DEFINITION(RESOURCE_ID);


-- =====================================================================
-- PostgreSQL Specific Version
-- =====================================================================
-- If using PostgreSQL, use the following DDL instead:

/*
-- IDN_VP_REQUEST for PostgreSQL
CREATE TABLE IF NOT EXISTS IDN_VP_REQUEST (
    REQUEST_ID VARCHAR(255) NOT NULL,
    TRANSACTION_ID VARCHAR(255) NOT NULL,
    CLIENT_ID VARCHAR(255) NOT NULL,
    NONCE VARCHAR(255) NOT NULL,
    PRESENTATION_DEFINITION_ID VARCHAR(255),
    RESPONSE_URI VARCHAR(2048),
    RESPONSE_MODE VARCHAR(50) DEFAULT 'direct_post',
    REQUEST_JWT TEXT,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    EXPIRES_AT BIGINT NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (REQUEST_ID),
    UNIQUE (TRANSACTION_ID, TENANT_ID)
);

-- IDN_VP_SUBMISSION for PostgreSQL
CREATE TABLE IF NOT EXISTS IDN_VP_SUBMISSION (
    ID SERIAL,
    SUBMISSION_ID VARCHAR(255) NOT NULL,
    REQUEST_ID VARCHAR(255) NOT NULL,
    VP_TOKEN TEXT,
    PRESENTATION_SUBMISSION TEXT,
    ERROR VARCHAR(255),
    ERROR_DESCRIPTION TEXT,
    VERIFICATION_STATUS VARCHAR(50),
    VERIFICATION_RESULT TEXT,
    SUBMITTED_AT BIGINT NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (ID),
    UNIQUE (SUBMISSION_ID, TENANT_ID)
);

-- IDN_PRESENTATION_DEFINITION for PostgreSQL
CREATE TABLE IF NOT EXISTS IDN_PRESENTATION_DEFINITION (
    DEFINITION_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DEFINITION_JSON TEXT NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (DEFINITION_ID),
    UNIQUE (NAME, TENANT_ID)
);

-- IDN_APPLICATION_PRESENTATION_DEFINITION for PostgreSQL
CREATE TABLE IF NOT EXISTS IDN_APPLICATION_PRESENTATION_DEFINITION (
    APPLICATION_ID VARCHAR(255) NOT NULL,
    PRESENTATION_DEFINITION_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (APPLICATION_ID, TENANT_ID),
    FOREIGN KEY (PRESENTATION_DEFINITION_ID, TENANT_ID) REFERENCES IDN_PRESENTATION_DEFINITION(DEFINITION_ID, TENANT_ID) ON DELETE CASCADE
);

-- Indexes (same as above)
CREATE INDEX IDX_VP_REQ_TRANSACTION_ID ON IDN_VP_REQUEST(TRANSACTION_ID, TENANT_ID);
CREATE INDEX IDX_VP_REQ_STATUS ON IDN_VP_REQUEST(STATUS, TENANT_ID);
CREATE INDEX IDX_VP_REQ_EXPIRES ON IDN_VP_REQUEST(EXPIRES_AT, STATUS);
CREATE INDEX IDX_VP_REQ_CLIENT_ID ON IDN_VP_REQUEST(CLIENT_ID, TENANT_ID);
CREATE INDEX IDX_VP_SUB_REQUEST_ID ON IDN_VP_SUBMISSION(REQUEST_ID, TENANT_ID);
CREATE INDEX IDX_VP_SUB_VERIFICATION ON IDN_VP_SUBMISSION(VERIFICATION_STATUS, TENANT_ID);
-- idx_pres_def_default removed
*/


-- =====================================================================
-- Oracle Specific Version
-- =====================================================================
-- If using Oracle, use the following DDL instead:

/*
-- IDN_VP_REQUEST for Oracle
CREATE TABLE IDN_VP_REQUEST (
    REQUEST_ID VARCHAR2(255) NOT NULL,
    TRANSACTION_ID VARCHAR2(255) NOT NULL,
    CLIENT_ID VARCHAR2(255) NOT NULL,
    NONCE VARCHAR2(255) NOT NULL,
    PRESENTATION_DEFINITION_ID VARCHAR2(255),
    PRESENTATION_DEFINITION CLOB,
    RESPONSE_URI VARCHAR2(2048),
    RESPONSE_MODE VARCHAR2(50) DEFAULT 'direct_post',
    REQUEST_JWT CLOB,
    STATUS VARCHAR2(50) DEFAULT 'ACTIVE' NOT NULL,
    EXPIRES_AT NUMBER(19) NOT NULL,
    TENANT_ID NUMBER(10) DEFAULT -1234,
    PRIMARY KEY (REQUEST_ID),
    UNIQUE (TRANSACTION_ID, TENANT_ID)
);

-- IDN_VP_SUBMISSION for Oracle
CREATE TABLE IDN_VP_SUBMISSION (
    ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    SUBMISSION_ID VARCHAR2(255) NOT NULL,
    REQUEST_ID VARCHAR2(255) NOT NULL,
    VP_TOKEN CLOB,
    PRESENTATION_SUBMISSION CLOB,
    ERROR VARCHAR2(255),
    ERROR_DESCRIPTION CLOB,
    VERIFICATION_STATUS VARCHAR2(50),
    VERIFICATION_RESULT CLOB,
    SUBMITTED_AT NUMBER(19) NOT NULL,
    TENANT_ID NUMBER(10) DEFAULT -1234,
    PRIMARY KEY (ID),
    UNIQUE (SUBMISSION_ID, TENANT_ID)
);

-- IDN_PRESENTATION_DEFINITION for Oracle
CREATE TABLE IDN_PRESENTATION_DEFINITION (
    DEFINITION_ID VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION CLOB,
    DEFINITION_JSON CLOB NOT NULL,
    TENANT_ID NUMBER(10) DEFAULT -1234,
    PRIMARY KEY (DEFINITION_ID),
    UNIQUE (NAME, TENANT_ID)
);

-- IDN_APPLICATION_PRESENTATION_DEFINITION for Oracle
CREATE TABLE IDN_APPLICATION_PRESENTATION_DEFINITION (
    APPLICATION_ID VARCHAR2(255) NOT NULL,
    PRESENTATION_DEFINITION_ID VARCHAR2(255) NOT NULL,
    TENANT_ID NUMBER(10) DEFAULT -1234,
    PRIMARY KEY (APPLICATION_ID, TENANT_ID),
    FOREIGN KEY (PRESENTATION_DEFINITION_ID, TENANT_ID) REFERENCES IDN_PRESENTATION_DEFINITION(DEFINITION_ID, TENANT_ID) ON DELETE CASCADE
);

-- Indexes for Oracle
CREATE INDEX IDX_VP_REQ_TRANSACTION_ID ON IDN_VP_REQUEST(TRANSACTION_ID, TENANT_ID);
CREATE INDEX IDX_VP_REQ_STATUS ON IDN_VP_REQUEST(STATUS, TENANT_ID);
CREATE INDEX IDX_VP_REQ_EXPIRES ON IDN_VP_REQUEST(EXPIRES_AT, STATUS);
CREATE INDEX IDX_VP_REQ_CLIENT_ID ON IDN_VP_REQUEST(CLIENT_ID, TENANT_ID);
CREATE INDEX IDX_VP_SUB_REQUEST_ID ON IDN_VP_SUBMISSION(REQUEST_ID, TENANT_ID);
CREATE INDEX IDX_VP_SUB_VERIFICATION ON IDN_VP_SUBMISSION(VERIFICATION_STATUS, TENANT_ID);
-- idx_pres_def_default removed
*/


-- =====================================================================
-- MS SQL Server Specific Version
-- =====================================================================
-- If using MS SQL Server, use the following DDL instead:

/*
-- IDN_VP_REQUEST for MS SQL
CREATE TABLE IDN_VP_REQUEST (
    REQUEST_ID VARCHAR(255) NOT NULL,
    TRANSACTION_ID VARCHAR(255) NOT NULL,
    CLIENT_ID VARCHAR(255) NOT NULL,
    NONCE VARCHAR(255) NOT NULL,
    PRESENTATION_DEFINITION_ID VARCHAR(255),
    PRESENTATION_DEFINITION NVARCHAR(MAX),
    RESPONSE_URI VARCHAR(2048),
    RESPONSE_MODE VARCHAR(50) DEFAULT 'direct_post',
    REQUEST_JWT NVARCHAR(MAX),
    STATUS VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    EXPIRES_AT BIGINT NOT NULL,
    TENANT_ID INT DEFAULT -1234,
    PRIMARY KEY (REQUEST_ID),
    UNIQUE (TRANSACTION_ID, TENANT_ID)
);

-- IDN_VP_SUBMISSION for MS SQL
CREATE TABLE IDN_VP_SUBMISSION (
    ID INT IDENTITY(1,1),
    SUBMISSION_ID VARCHAR(255) NOT NULL,
    REQUEST_ID VARCHAR(255) NOT NULL,
    VP_TOKEN NVARCHAR(MAX),
    PRESENTATION_SUBMISSION NVARCHAR(MAX),
    ERROR VARCHAR(255),
    ERROR_DESCRIPTION NVARCHAR(MAX),
    VERIFICATION_STATUS VARCHAR(50),
    VERIFICATION_RESULT NVARCHAR(MAX),
    SUBMITTED_AT BIGINT NOT NULL,
    TENANT_ID INT DEFAULT -1234,
    PRIMARY KEY (ID),
    UNIQUE (SUBMISSION_ID, TENANT_ID)
);

-- IDN_PRESENTATION_DEFINITION for MS SQL
CREATE TABLE IDN_PRESENTATION_DEFINITION (
    DEFINITION_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(MAX),
    DEFINITION_JSON NVARCHAR(MAX) NOT NULL,
    TENANT_ID INT DEFAULT -1234,
    PRIMARY KEY (DEFINITION_ID),
    UNIQUE (NAME, TENANT_ID)
);

-- IDN_APPLICATION_PRESENTATION_DEFINITION for MS SQL
CREATE TABLE IDN_APPLICATION_PRESENTATION_DEFINITION (
    APPLICATION_ID VARCHAR(255) NOT NULL,
    PRESENTATION_DEFINITION_ID VARCHAR(255) NOT NULL,
    TENANT_ID INT DEFAULT -1234,
    PRIMARY KEY (APPLICATION_ID, TENANT_ID),
    FOREIGN KEY (PRESENTATION_DEFINITION_ID, TENANT_ID) REFERENCES IDN_PRESENTATION_DEFINITION(DEFINITION_ID, TENANT_ID) ON DELETE CASCADE
);

-- Indexes for MS SQL
CREATE INDEX IDX_VP_REQ_TRANSACTION_ID ON IDN_VP_REQUEST(TRANSACTION_ID, TENANT_ID);
CREATE INDEX IDX_VP_REQ_STATUS ON IDN_VP_REQUEST(STATUS, TENANT_ID);
CREATE INDEX IDX_VP_REQ_EXPIRES ON IDN_VP_REQUEST(EXPIRES_AT, STATUS);
CREATE INDEX IDX_VP_REQ_CLIENT_ID ON IDN_VP_REQUEST(CLIENT_ID, TENANT_ID);
CREATE INDEX IDX_VP_SUB_REQUEST_ID ON IDN_VP_SUBMISSION(REQUEST_ID, TENANT_ID);
CREATE INDEX IDX_VP_SUB_VERIFICATION ON IDN_VP_SUBMISSION(VERIFICATION_STATUS, TENANT_ID);
*/
