-- =====================================================================
-- OpenID4VP Database Schema for H2 (WSO2 Identity Server)
-- Combined schema for all OpenID4VP tables
-- Run this script against the WSO2_CARBON_DB H2 database
-- =====================================================================

-- ---------------------------------------------------------------------
-- Table: IDN_VP_REQUEST
-- Description: Stores VP (Verifiable Presentation) authorization requests
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS IDN_VP_REQUEST (
    ID INTEGER AUTO_INCREMENT,
    REQUEST_ID VARCHAR(255) NOT NULL,
    TRANSACTION_ID VARCHAR(255) NOT NULL,
    CLIENT_ID VARCHAR(255) NOT NULL,
    NONCE VARCHAR(255) NOT NULL,
    PRESENTATION_DEFINITION_ID VARCHAR(255),
    PRESENTATION_DEFINITION CLOB,
    RESPONSE_URI VARCHAR(2048),
    RESPONSE_MODE VARCHAR(50) DEFAULT 'direct_post',
    REQUEST_JWT CLOB,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT BIGINT NOT NULL,
    EXPIRES_AT BIGINT NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (ID),
    UNIQUE (REQUEST_ID, TENANT_ID),
    UNIQUE (TRANSACTION_ID, TENANT_ID)
);

-- Indexes for VP_REQUEST table
CREATE INDEX IF NOT EXISTS IDX_VP_REQ_TRANSACTION_ID ON IDN_VP_REQUEST(TRANSACTION_ID, TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_VP_REQ_STATUS ON IDN_VP_REQUEST(STATUS, TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_VP_REQ_EXPIRES ON IDN_VP_REQUEST(EXPIRES_AT, STATUS);
CREATE INDEX IF NOT EXISTS IDX_VP_REQ_CLIENT_ID ON IDN_VP_REQUEST(CLIENT_ID, TENANT_ID);

-- ---------------------------------------------------------------------
-- Table: IDN_PRESENTATION_DEFINITION
-- Description: Stores presentation definition templates
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS IDN_PRESENTATION_DEFINITION (
    DEFINITION_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION CLOB,
    DEFINITION_JSON CLOB NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (DEFINITION_ID),
    UNIQUE (NAME, TENANT_ID)
);

-- Indexes for PRESENTATION_DEFINITION table
-- idx_pres_def_default removed as column is dropped


-- ---------------------------------------------------------------------
-- Table: IDN_APPLICATION_PRESENTATION_DEFINITION
-- Description: Maps applications to their presentation definitions
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS IDN_APPLICATION_PRESENTATION_DEFINITION (
    APPLICATION_ID VARCHAR(255) NOT NULL,
    PRESENTATION_DEFINITION_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER DEFAULT -1234,
    PRIMARY KEY (APPLICATION_ID, TENANT_ID),
    FOREIGN KEY (PRESENTATION_DEFINITION_ID, TENANT_ID) REFERENCES IDN_PRESENTATION_DEFINITION(DEFINITION_ID, TENANT_ID) ON DELETE CASCADE
);

-- Indexes for APPLICATION_PRESENTATION_DEFINITION table
CREATE INDEX IF NOT EXISTS IDX_APP_PRES_DEF_APP_ID ON IDN_APPLICATION_PRESENTATION_DEFINITION(APPLICATION_ID, TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_APP_PRES_DEF_PRES_ID ON IDN_APPLICATION_PRESENTATION_DEFINITION(PRESENTATION_DEFINITION_ID, TENANT_ID);
CREATE INDEX IF NOT EXISTS IDX_APP_PRES_DEF_TENANT ON IDN_APPLICATION_PRESENTATION_DEFINITION(TENANT_ID);

-- ---------------------------------------------------------------------
-- Table: IDN_DID_KEYS
-- Description: Stores persistent keys for DIDs (especially Ed25519)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS IDN_DID_KEYS (
    TENANT_ID INTEGER NOT NULL,
    KEY_ID VARCHAR(255) NOT NULL,
    ALGORITHM VARCHAR(50) NOT NULL,
    PUBLIC_KEY BLOB,
    PRIVATE_KEY BLOB,
    CREATED_AT BIGINT NOT NULL,
    PRIMARY KEY (TENANT_ID, KEY_ID)
);
